'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { onAuthStateChanged, User } from 'firebase/auth';
import { auth } from '@/lib/firebase';

type Metrics = { tenants: number; activeTenants: number; users: number; activeUsers: number; sales: number; grossSales: number; expenses: number; net: number; failedPayments: number };
type Data = { metrics: Metrics; subscriptionCounts: Record<string, number>; planCounts: Record<string, number>; recentTenants: { id: string; name: string; plan: string; status: string }[] };
const statusLabels: Record<string, string> = { active: 'Activas', trialing: 'En prueba', past_due: 'Pago pendiente', canceled: 'Canceladas', inactive: 'Sin suscripción' };

function SuperadminContent() { const router = useRouter(); const [user, setUser] = useState<User | null>(null); const [loadingAuth, setLoadingAuth] = useState(true); const [data, setData] = useState<Data | null>(null); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('');
  useEffect(() => onAuthStateChanged(auth, (current) => { setUser(current); setLoadingAuth(false); }), []);
  useEffect(() => { if (!user) { if (!loadingAuth) { setLoading(false); router.replace('/'); } return; } void (async () => { try { const response = await fetch('/api/superadmin/metrics', { headers: { Authorization: `Bearer ${await user.getIdToken()}` }, cache: 'no-store' }); const result = await response.json(); if (!response.ok) throw new Error(result.error || 'No tienes acceso al panel global.'); setData(result); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo cargar el panel.'); } finally { setLoading(false); } })(); }, [user, loadingAuth, router]);
  if (loadingAuth || loading) return <div className="workspace-loading">Cargando panel global...</div>; if (!data) return <main className="superadmin-denied"><div><b>Nexo<span>Flow</span></b><h1>Acceso restringido</h1><p>{message || 'Este panel es exclusivo para superadministradores.'}</p><button className="button" onClick={() => router.replace('/')}>Volver al inicio</button></div></main>;
  const cards = [['Tenants', data.metrics.tenants, 'empresas registradas'], ['Activos', data.metrics.activeTenants, 'suscripciones activas'], ['Usuarios', data.metrics.activeUsers, 'usuarios activos'], ['Ventas', `$${data.metrics.grossSales.toFixed(2)}`, `${data.metrics.sales} operaciones`], ['Gastos', `$${data.metrics.expenses.toFixed(2)}`, 'registrados globalmente'], ['Resultado', `$${data.metrics.net.toFixed(2)}`, 'ventas menos gastos']];
  return <main className="superadmin-shell"><header className="superadmin-header"><div><span className="superadmin-kicker">NexoFlow / Control global</span><h1>Panel de plataforma</h1><p>Métricas agregadas de todos los tenants SaaS.</p></div><button className="button button-secondary" onClick={() => router.refresh()}>Actualizar datos ↻</button></header><div className="superadmin-alert">{data.metrics.failedPayments} pagos fallidos detectados en las alertas de los tenants.</div><div className="superadmin-cards">{cards.map(([label, value, note]) => <div className="superadmin-card" key={String(label)}><small>{label}</small><strong>{value}</strong><span>{note}</span></div>)}</div><div className="superadmin-grid"><section className="superadmin-panel"><div className="superadmin-panel-head"><div><small>Suscripciones</small><h2>Estado global</h2></div></div>{Object.entries(data.subscriptionCounts).map(([key, value]) => <div className="superadmin-row" key={key}><span>{statusLabels[key] || key}</span><div><i style={{ width: `${Math.min(100, value / Math.max(data.metrics.tenants, 1) * 100)}%` }} /></div><b>{value}</b></div>)}<div className="superadmin-panel-head plans-head"><div><small>Planes</small><h2>Distribución</h2></div></div>{Object.entries(data.planCounts).map(([key, value]) => <div className="plan-count" key={key}><span>{key}</span><b>{value} tenant(s)</b></div>)}</section><section className="superadmin-panel"><div className="superadmin-panel-head"><div><small>Actividad reciente</small><h2>Últimos tenants</h2></div></div>{data.recentTenants.map((tenant) => <div className="tenant-row" key={tenant.id}><span>{tenant.name.slice(0, 1).toUpperCase()}</span><div><b>{tenant.name}</b><small>Plan {tenant.plan} · {statusLabels[tenant.status] || tenant.status}</small></div><em className={tenant.status === 'active' ? 'tenant-active' : ''}>{tenant.status}</em></div>)}</section></div></main>;
}
export default function SuperadminPage() { return <SuperadminContent />; }
