import type { User } from '@supabase/supabase-js';
import { getSupabaseBrowser } from '@/lib/supabase/client';
export type MfaEnrollment = { factorId: string; challengeId: string; phoneNumber: string };
export type MfaChallenge = { factorId: string; challengeId: string };
export function getMfaErrorCode(error: unknown): string { if (error instanceof Error) return error.message; if (typeof error === 'object' && error !== null && 'code' in error && typeof error.code === 'string') return error.code; return ''; }
export async function hasEnrolledMfa(_user: User): Promise<boolean> { const result = await getSupabaseBrowser().auth.mfa.listFactors(); if (result.error) return false; return (result.data.all || []).some((factor) => factor.status === 'verified'); }
export async function beginPhoneMfaEnrollment(phoneNumber: string, _containerId: string): Promise<MfaEnrollment> { const value = phoneNumber.trim(); if (!/^\+[1-9]\d{7,14}$/.test(value)) throw new Error('PHONE_FORMAT'); const enrolled = await getSupabaseBrowser().auth.mfa.enroll({ factorType: 'phone', friendlyName: `Teléfono ${value}`, phone: value } as never); if (enrolled.error || !enrolled.data) throw new Error(enrolled.error?.message || 'MFA_ENROLL_FAILED'); const challenge = await getSupabaseBrowser().auth.mfa.challenge({ factorId: enrolled.data.id }); if (challenge.error || !challenge.data) throw new Error(challenge.error?.message || 'MFA_CHALLENGE_FAILED'); return { factorId: enrolled.data.id, challengeId: challenge.data.id, phoneNumber: value }; }
export async function completePhoneMfaEnrollment(enrollment: MfaEnrollment, code: string): Promise<void> { if (!/^\d{6}$/.test(code.trim())) throw new Error('CODE_FORMAT'); const result = await getSupabaseBrowser().auth.mfa.verify({ factorId: enrollment.factorId, challengeId: enrollment.challengeId, code: code.trim() }); if (result.error) throw new Error(result.error.message); }
export async function beginMfaSignIn(_error: unknown, _containerId: string): Promise<MfaChallenge> { throw new Error('MFA_CHALLENGE_REQUIRED'); }
export function getMfaResolver(_error: unknown): null { return null; }
export async function completeMfaSignIn(_resolver: unknown, _verificationId: string, _code: string): Promise<void> { throw new Error('MFA_CHALLENGE_REQUIRED'); }
