'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { TenantProvider, useTenant } from '@/components/tenant/TenantProvider';

type Notice = { id: string; type: string; title: string; message: string; read: boolean; createdAt?: unknown };
function NotificationsContent() { const router = useRouter(); const { authUser, tenant, member, loading: tenantLoading } = useTenant(); const [items, setItems] = useState<Notice[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState('');
  async function load() { if (!authUser || !tenant) return; setLoading(true); try { const response = await fetch('/api/notifications', { headers: { Authorization: `Bearer ${await authUser.getIdToken()}`, 'x-tenant-id': tenant.id }, cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'No se pudieron cargar las alertas.'); setItems(data.notifications || []); } catch (error) { setMessage(error instanceof Error ? error.message : 'Error cargando alertas.'); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [authUser, tenant]);
  async function markRead(id: string) { if (!authUser || !tenant) return; try { await fetch('/api/notifications', { method: 'PATCH', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${await authUser.getIdToken()}`, 'x-tenant-id': tenant.id }, body: JSON.stringify({ id }) }); setItems((current) => current.map((item) => item.id === id ? { ...item, read: true } : item)); } catch { setMessage('No se pudo marcar la alerta.'); } }
  if (tenantLoading || loading) return <div className="workspace-loading">Cargando alertas...</div>; if (!authUser || !tenant || !member) { router.replace('/'); return null; }
  const unread = items.filter((item) => !item.read).length; const icon: Record<string, string> = { payment_failed: '!', renewal_upcoming: '◷', subscription_updated: '✓' };
  return <main className="workspace-page"><aside className="workspace-sidebar"><div className="onboarding-brand"><span className="brand-mark-icon">N</span><b>Nexo<span>Flow</span></b></div><div className="workspace-company"><span>{tenant.name.slice(0, 1).toUpperCase()}</span><div><b>{tenant.name}</b><small>Plan {tenant.plan || 'Starter'}</small></div></div><nav><a onClick={() => router.push('/workspace')}>▦ <span>Resumen</span></a><a className="active">♢ <span>Notificaciones</span>{unread > 0 && <em className="notice-count">{unread}</em>}</a><a onClick={() => router.push('/workspace/billing')}>◈ <span>Plan y facturación</span></a></nav></aside><section className="workspace-main notifications-main"><header className="notifications-header"><div><button className="text-link" onClick={() => router.push('/workspace')}>← Resumen</button><div className="eyebrow catalog-eyebrow">Tu espacio / Alertas</div><h1>Notificaciones</h1><p>Alertas importantes de la suscripción de <strong>{tenant.name}</strong>.</p></div></header>{message && <div className="catalog-message">{message}</div>}<div className="notifications-panel">{items.length === 0 ? <div className="catalog-empty"><div className="empty-spark">♢</div><h2>Todo está tranquilo</h2><p>Aquí aparecerán pagos fallidos, renovaciones próximas y cambios de suscripción.</p></div> : items.map((item) => <article className={`notice-card ${item.read ? 'read' : ''}`} key={item.id}><span className={`notice-icon ${item.type}`}>{icon[item.type] || 'i'}</span><div><h3>{item.title}</h3><p>{item.message}</p><small>{item.createdAt ? 'Alerta de facturación' : 'Nueva alerta'}</small></div>{!item.read && <button onClick={() => void markRead(item.id)}>Marcar leída</button>}</article>)}</div></section></main>; }
export default function NotificationsPage() { return <TenantProvider><NotificationsContent /></TenantProvider>; }
