import { NextRequest, NextResponse } from 'next/server';
import { getAdminDb } from '@/lib/firebaseAdmin';
import { requireTenantPermission, tenantErrorResponse, type TenantRole } from '@/lib/tenant';
import { writeImmutableAudit } from '@/lib/audit';
export const runtime = 'nodejs';
const deliveryRoles: TenantRole[] = ['owner', 'admin', 'gerente', 'supervisor_sucursal', 'chofer', 'despachador'];
function text(value: unknown, max = 180) { return typeof value === 'string' ? value.trim().slice(0, max) : ''; }
export async function GET(request: NextRequest) { try { const context = await requireTenantPermission(request, 'sales', 'view'); const tenant = getAdminDb().collection('tenants').doc(context.tenantId); let query = tenant.collection('deliveries').orderBy('createdAt', 'desc').limit(25); if (context.role === 'chofer') query = tenant.collection('deliveries').where('driverUid', '==', context.uid).orderBy('createdAt', 'desc').limit(25); const snapshot = await query.get(); return NextResponse.json({ ok: true, deliveries: snapshot.docs.map((item) => ({ id: item.id, ...item.data() })) }); } catch (error: unknown) { const response = tenantErrorResponse(error); return NextResponse.json(response.body, { status: response.status }); } }
export async function POST(request: NextRequest) { try { const context = await requireTenantPermission(request, 'sales', 'create'); if (!deliveryRoles.includes(context.role)) return NextResponse.json({ error: 'Tu rol no puede crear entregas.' }, { status: 403 }); const body = await request.json(); const saleId = text(body.saleId, 120); const driverUid = text(body.driverUid, 120); if (!saleId) return NextResponse.json({ error: 'La venta es obligatoria.' }, { status: 400 }); const db = getAdminDb(); const tenant = db.collection('tenants').doc(context.tenantId); const sale = await tenant.collection('sales').doc(saleId).get(); if (!sale.exists) return NextResponse.json({ error: 'La venta no existe en este tenant.' }, { status: 404 }); const ref = tenant.collection('deliveries').doc(); const data = sale.data() || {}; const delivery = { saleId, customerId: data.customerId || null, customerName: data.customerName || 'Cliente mostrador', address: text(body.address, 300) || data.customerAddress || '', driverUid: driverUid || (context.role === 'chofer' ? context.uid : null), status: 'pending', createdBy: context.uid, createdAt: new Date(), updatedAt: new Date() }; await ref.create(delivery); await writeImmutableAudit({ tenantId: context.tenantId, actor: context, action: 'delivery.created', entity: 'delivery', entityId: ref.id, after: delivery, result: 'success' }); return NextResponse.json({ ok: true, delivery: { id: ref.id, ...delivery } }, { status: 201 }); } catch (error: unknown) { const response = tenantErrorResponse(error); return NextResponse.json(response.body, { status: response.status }); } }
export async function PATCH(request: NextRequest) { try { const context = await requireTenantPermission(request, 'sales', 'edit'); const body = await request.json(); const id = text(body.id, 120); if (!id) return NextResponse.json({ error: 'Entrega inválida.' }, { status: 400 }); const ref = getAdminDb().collection('tenants').doc(context.tenantId).collection('deliveries').doc(id); const snapshot = await ref.get(); if (!snapshot.exists) return NextResponse.json({ error: 'Entrega no encontrada.' }, { status: 404 }); const current = snapshot.data() || {}; if (context.role === 'chofer' && current.driverUid !== context.uid) return NextResponse.json({ error: 'Solo puedes actualizar tus entregas.' }, { status: 403 }); const status = body.status === 'delivered' ? 'delivered' : body.status === 'pending' ? 'pending' : ''; if (!status) return NextResponse.json({ error: 'Estado inválido.' }, { status: 400 }); await ref.update({ status, deliveredAt: status === 'delivered' ? new Date() : null, updatedAt: new Date(), updatedBy: context.uid }); await writeImmutableAudit({ tenantId: context.tenantId, actor: context, action: `delivery.${status}`, entity: 'delivery', entityId: id, before: { status: current.status }, after: { status }, result: 'success' }); return NextResponse.json({ ok: true, id, status }); } catch (error: unknown) { const response = tenantErrorResponse(error); return NextResponse.json(response.body, { status: response.status }); } }
