'use client';
import { FormEvent,useCallback,useEffect,useMemo,useRef,useState } from 'react';
import { useRouter } from 'next/navigation';
import { WorkspaceSidebar } from '@/components/workspace/WorkspaceSidebar';
import { BarcodeScanner } from '@/components/workspace/BarcodeScanner';
import { useTenant } from '@/components/tenant/TenantProvider';
import { formatMoney } from '@/lib/currency';
import { printElement } from '@/lib/print';
import { describeRequestError } from '@/lib/connectivity';

type Product={id:string;name:string;sku:string;barcode?:string;price:number};type Customer={id:string;name:string};type Line={productId:string;name:string;sku:string;quantity:number};type Quote={id:string;quote_number:number;branch_id:string;status:string;valid_until:string;total:number;subtotal:number;tax_amount:number;currency:string;notes?:string;terms?:string;rejection_reason?:string;converted_presale_id?:string;customers?:{name:string}|null;branches?:{name:string}|null;quote_items?:Array<{id:string;description:string;sku:string;quantity:number;unit_price:number;line_total:number}>};
const statusLabel:Record<string,string>={draft:'Borrador',sent:'Enviada',accepted:'Aceptada',rejected:'Rechazada',expired:'Vencida',converted:'En caja'};
export default function QuotesPage(){const router=useRouter();const {authUser,tenant,member,organization,activeBranchId,loading:tenantLoading}=useTenant();const [quotes,setQuotes]=useState<Quote[]>([]),[products,setProducts]=useState<Product[]>([]),[customers,setCustomers]=useState<Customer[]>([]),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[showForm,setShowForm]=useState(false),[scanner,setScanner]=useState(false),[selected,setSelected]=useState<Quote|null>(null),[search,setSearch]=useState(''),[customerId,setCustomerId]=useState(''),[validUntil,setValidUntil]=useState(()=>new Date(Date.now()+7*86400000).toISOString().slice(0,10)),[notes,setNotes]=useState(''),[terms,setTerms]=useState('Precios válidos hasta la fecha indicada.'),[lines,setLines]=useState<Line[]>([]);const printRef=useRef<HTMLDivElement>(null);
 const headers=useCallback(async()=>({'Content-Type':'application/json',Authorization:`Bearer ${await authUser!.getIdToken()}`,'x-tenant-id':tenant!.id}),[authUser,tenant]);
 const load=useCallback(async()=>{if(!authUser||!tenant)return;setLoading(true);try{const h=await headers();const [qr,pr,cr]=await Promise.all([fetch('/api/quotes',{headers:h,cache:'no-store'}),fetch('/api/catalog?pageSize=25',{headers:{...h,'x-branch-id':activeBranchId||''},cache:'no-store'}),fetch('/api/contacts?type=customer&pageSize=100',{headers:h,cache:'no-store'})]);const [q,p,c]=await Promise.all([qr.json(),pr.json(),cr.json()]);if(!qr.ok)throw new Error(q.error);if(!pr.ok)throw new Error(p.error);if(!cr.ok)throw new Error(c.error);setQuotes(q.quotes||[]);setProducts(p.products||[]);setCustomers(c.contacts||[])}catch(e){setMessage(describeRequestError(e,'No se pudieron cargar las cotizaciones.'))}finally{setLoading(false)}},[authUser,tenant,headers,activeBranchId]);useEffect(()=>{void load()},[load]);
 function add(product:Product){setLines(old=>{const found=old.find(x=>x.productId===product.id);return found?old.map(x=>x.productId===product.id?{...x,quantity:x.quantity+1}:x):[...old,{productId:product.id,name:product.name,sku:product.sku,quantity:1}]})}
 function detect(value:string){const p=products.find(x=>[x.barcode,x.sku].some(v=>v?.toLowerCase()===value.toLowerCase()));if(p){add(p);setMessage(`${p.name} agregado.`)}else setMessage('No encontramos un producto con ese código.')}
 async function create(e:FormEvent){e.preventDefault();if(!activeBranchId){setMessage('Selecciona una sucursal.');return}setSaving(true);try{const r=await fetch('/api/quotes',{method:'POST',headers:await headers(),body:JSON.stringify({branchId:activeBranchId,customerId,validUntil,notes,terms,currency:tenant?.currency||'NIO',items:lines})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(`Cotización #${d.quote.quoteNumber} creada con precios comerciales.`);setShowForm(false);setLines([]);await load()}catch(err){setMessage(describeRequestError(err,'No se pudo crear la cotización.'))}finally{setSaving(false)}}
 async function action(q:Quote,action:string){let reason='';if(action==='reject'){reason=window.prompt('Motivo del rechazo:')||'';if(!reason)return}setSaving(true);try{const r=await fetch(`/api/quotes/${q.id}`,{method:'PATCH',headers:await headers(),body:JSON.stringify({action,reason})});const d=await r.json();if(!r.ok)throw new Error(d.error);setMessage(action==='convert'?'Cotización enviada a Caja como preventa.':'Cotización actualizada.');await load();const refreshed=(await (await fetch(`/api/quotes?id=${q.id}`,{headers:await headers()})).json()).quotes?.[0];if(refreshed)setSelected(refreshed)}catch(e){setMessage(describeRequestError(e,'No se pudo actualizar.'))}finally{setSaving(false)}}
 const visible=useMemo(()=>quotes.filter(q=>`${q.quote_number} ${q.customers?.name||''} ${q.status}`.toLowerCase().includes(search.toLowerCase())),[quotes,search]);if(tenantLoading||loading)return <div className="workspace-loading">Cargando cotizaciones…</div>;if(!authUser||!tenant||!member){router.replace('/');return null}
 return <main className="workspace-page"><WorkspaceSidebar/><section className="workspace-main quote-main"><header className="quote-header"><div><div className="eyebrow">Operación / Cotizaciones</div><h1>Cotizaciones</h1><p>Precios comerciales seguros, vigencia y conversión protegida a Caja.</p></div><button className="button" onClick={()=>setShowForm(true)}>+ Nueva cotización</button></header>{message&&<div className="catalog-message">{message}</div>}<div className="quote-toolbar"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar número, cliente o estado"/><span>{visible.length} cotizaciones</span></div><div className="quote-grid">{visible.map(q=><article className="quote-card" key={q.id}><div><span className={`quote-status status-${q.status}`}>{statusLabel[q.status]||q.status}</span><h2>#{String(q.quote_number).padStart(6,'0')}</h2><p>{q.customers?.name||'Cliente mostrador'} · {q.branches?.name||'Sucursal'}</p></div><strong>{formatMoney(Number(q.total),q.currency)}</strong><small>Válida hasta {q.valid_until}</small><div className="quote-actions"><button onClick={()=>setSelected(q)}>Ver</button>{q.status==='draft'&&<button disabled={saving} onClick={()=>void action(q,'send')}>Enviar</button>}{q.status==='sent'&&<button disabled={saving} onClick={()=>void action(q,'accept')}>Aceptar</button>}{['sent','accepted'].includes(q.status)&&<button disabled={saving} onClick={()=>void action(q,'convert')}>Enviar a Caja</button>}{['draft','sent','accepted'].includes(q.status)&&<button disabled={saving} onClick={()=>void action(q,'reject')}>Rechazar</button>}</div></article>)}</div>
 {showForm&&<div className="modal-backdrop" onClick={()=>setShowForm(false)}><div className="catalog-modal quote-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setShowForm(false)}>×</button><div className="eyebrow">Nueva cotización</div><h2>Productos y vigencia</h2><form onSubmit={create}><div className="form-two"><label>Sucursal<select required value={activeBranchId||''} disabled><option value="">Selecciona en el encabezado</option>{organization?.branches.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select></label><label>Cliente<select value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Cliente mostrador</option>{customers.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label></div><label>Válida hasta<input required type="date" min={new Date().toISOString().slice(0,10)} value={validUntil} onChange={e=>setValidUntil(e.target.value)}/></label><div className="quote-product-picker"><select onChange={e=>{const p=products.find(x=>x.id===e.target.value);if(p)add(p);e.target.value=''}} defaultValue=""><option value="">Agregar producto…</option>{products.map(p=><option key={p.id} value={p.id}>{p.name} · {p.sku}</option>)}</select><button type="button" className="button button-secondary" onClick={()=>setScanner(true)}>Escanear</button></div><div className="quote-lines">{lines.map(line=><div key={line.productId}><span><b>{line.name}</b><small>{line.sku}</small></span><input aria-label={`Cantidad de ${line.name}`} type="number" min="1" step="1" value={line.quantity} onChange={e=>setLines(old=>old.map(x=>x.productId===line.productId?{...x,quantity:Number(e.target.value)}:x))}/><button type="button" onClick={()=>setLines(old=>old.filter(x=>x.productId!==line.productId))}>×</button></div>)}</div><label>Notas<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label><label>Términos<textarea value={terms} onChange={e=>setTerms(e.target.value)}/></label><button className="button" disabled={saving||!lines.length}>{saving?'Calculando precios…':'Crear cotización'}</button></form></div></div>}
 <BarcodeScanner open={scanner} onClose={()=>setScanner(false)} onDetected={detect}/>{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="catalog-modal quote-detail" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)}>×</button><div ref={printRef}><div className="eyebrow">Cotización #{String(selected.quote_number).padStart(6,'0')}</div><h2>{tenant.name}</h2><p>{selected.customers?.name||'Cliente mostrador'} · {selected.branches?.name||''}</p><p>Válida hasta: <b>{selected.valid_until}</b></p><div className="quote-detail-lines">{selected.quote_items?.map(i=><div key={i.id}><span>{i.description}<small>{i.quantity} × {formatMoney(Number(i.unit_price),selected.currency)}</small></span><b>{formatMoney(Number(i.line_total),selected.currency)}</b></div>)}</div><div className="quote-totals"><span>Subtotal <b>{formatMoney(Number(selected.subtotal),selected.currency)}</b></span><span>Impuestos <b>{formatMoney(Number(selected.tax_amount),selected.currency)}</b></span><strong>Total {formatMoney(Number(selected.total),selected.currency)}</strong></div>{selected.notes&&<p><b>Notas:</b> {selected.notes}</p>}{selected.terms&&<p><b>Términos:</b> {selected.terms}</p>}</div><button className="button" onClick={()=>printElement(printRef.current)}>Imprimir o compartir</button></div></div>}</section></main>}
