import { NextRequest, NextResponse } from 'next/server';
import { getSupabaseServer } from '@/lib/supabase/server';
import { requireSuperadmin, superadminErrorResponse } from '@/lib/superadmin';
import { getPriceId, getStripe, isPlanKey, PlanKey } from '@/lib/stripe';
import { notifyTenant } from '@/lib/notifications';

export const runtime = 'nodejs';
function text(value: unknown, max = 120) { return typeof value === 'string' ? value.trim().slice(0, max) : ''; }
async function audit(uid: string, tenantId: string, action: string, details: Record<string, unknown>) { const result = await getSupabaseServer().from('platform_audit').insert({ actor_uid: uid, tenant_id: tenantId, action, details }); if (result.error) throw new Error(result.error.message); }
export async function GET(request: NextRequest) {
  try { await requireSuperadmin(request); const result = await getSupabaseServer().from('tenants').select('id,legacy_firestore_id,slug,name,status,platform_status,timezone,currency,plan,subscription_status,stripe_customer_id,stripe_subscription_id,plan_managed_by,plan_changed_at,plan_changed_by,created_at,updated_at').order('created_at', { ascending: false }).limit(200); if (result.error) throw new Error(result.error.message); return NextResponse.json({ ok: true, tenants: result.data || [] }); }
  catch (error: unknown) { const response = superadminErrorResponse(error); return NextResponse.json(response.body, { status: response.status }); }
}
export async function PATCH(request: NextRequest) {
  try {
    const actor = await requireSuperadmin(request); const body = await request.json(); const tenantId = text(body.tenantId); const action = text(body.action); if (!tenantId) return NextResponse.json({ error: 'Tenant inválido.' }, { status: 400 });
    const currentResult = await getSupabaseServer().from('tenants').select('id,platform_status,plan,stripe_subscription_id').eq('id', tenantId).maybeSingle(); if (currentResult.error) throw new Error(currentResult.error.message); if (!currentResult.data) return NextResponse.json({ error: 'Tenant no encontrado.' }, { status: 404 }); const current = currentResult.data;
    if (action === 'suspend' || action === 'activate') { const platformStatus = action === 'suspend' ? 'suspended' : 'active'; const update = await getSupabaseServer().from('tenants').update({ platform_status: platformStatus, updated_at: new Date().toISOString() }).eq('id', tenantId); if (update.error) throw new Error(update.error.message); await audit(actor.uid, tenantId, action, { previousStatus: current.platform_status || 'active' }); if (action === 'suspend') await notifyTenant(tenantId, 'subscription_updated', 'Empresa suspendida', 'El acceso de tu empresa fue suspendido por un administrador de la plataforma. Contacta soporte para revisar el caso.', { platformStatus }); return NextResponse.json({ ok: true, tenantId, platformStatus }); }
    if (action === 'change_plan') { const plan = body.plan as PlanKey; if (!isPlanKey(plan)) return NextResponse.json({ error: 'Plan inválido.' }, { status: 400 }); const subscriptionId = text(current.stripe_subscription_id); if (subscriptionId) { const stripe = getStripe(); const subscription = await stripe.subscriptions.retrieve(subscriptionId); const item = subscription.items.data[0]; if (item) await stripe.subscriptions.update(subscriptionId, { items: [{ id: item.id, price: getPriceId(plan) }], proration_behavior: 'create_prorations' }); } const update = await getSupabaseServer().from('tenants').update({ plan, plan_managed_by: 'superadmin', plan_changed_at: new Date().toISOString(), plan_changed_by: actor.uid, updated_at: new Date().toISOString() }).eq('id', tenantId); if (update.error) throw new Error(update.error.message); await audit(actor.uid, tenantId, action, { previousPlan: current.plan || 'starter', plan, stripeSynchronized: Boolean(subscriptionId) }); return NextResponse.json({ ok: true, tenantId, plan, stripeSynchronized: Boolean(subscriptionId) }); }
    return NextResponse.json({ error: 'Acción no válida.' }, { status: 400 });
  } catch (error: unknown) { const message = error instanceof Error ? error.message : ''; if (message.startsWith('STRIPE_')) return NextResponse.json({ error: 'Stripe no está configurado para cambiar este plan automáticamente.' }, { status: 503 }); const response = superadminErrorResponse(error); return NextResponse.json(response.body, { status: response.status }); }
}
