'use client';

import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { TenantProvider, useTenant } from '@/components/tenant/TenantProvider';

type Plan = { name: string; description: string; priceEnv: string };
type Billing = { plans: Record<string, Plan>; subscription: { plan: string; status: string; currentPeriodEnd: unknown; cancelAtPeriodEnd: boolean; hasPaymentCustomer: boolean } };

function BillingContent() {
  const router = useRouter(); const { authUser, tenant, member, loading: tenantLoading } = useTenant(); const [billing, setBilling] = useState<Billing | null>(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState('');
  async function load() { if (!authUser || !tenant) return; setLoading(true); try { const response = await fetch('/api/billing', { headers: { Authorization: `Bearer ${await authUser.getIdToken()}`, 'x-tenant-id': tenant.id }, cache: 'no-store' }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'No se pudo cargar facturación.'); setBilling(data); } catch (error) { setMessage(error instanceof Error ? error.message : 'Error cargando facturación.'); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [authUser, tenant]);
  useEffect(() => { const params = new URLSearchParams(window.location.search); if (params.get('success')) setMessage('Checkout completado. Stripe confirmará la suscripción mediante webhook.'); if (params.get('canceled')) setMessage('El checkout fue cancelado; no se realizó ningún cobro.'); }, []);
  async function action(action: string, plan?: string) { if (!authUser || !tenant) return; setSaving(true); setMessage(''); try { const response = await fetch('/api/billing', { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${await authUser.getIdToken()}`, 'x-tenant-id': tenant.id }, body: JSON.stringify({ action, plan }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'No se pudo abrir facturación.'); if (data.url) window.location.assign(data.url); } catch (error) { setMessage(error instanceof Error ? error.message : 'No se pudo iniciar la operación.'); } finally { setSaving(false); } }
  if (tenantLoading || loading || !billing) return <div className="workspace-loading">Cargando suscripción...</div>;
  if (!authUser || !tenant || !member) { router.replace('/'); return null; }
  const statusLabels: Record<string, string> = { active: 'Activa', trialing: 'En prueba', past_due: 'Pago pendiente', canceled: 'Cancelada', inactive: 'Sin suscripción' };
  return <main className="workspace-page"><aside className="workspace-sidebar"><div className="onboarding-brand"><span className="brand-mark-icon">N</span><b>Nexo<span>Flow</span></b></div><div className="workspace-company"><span>{tenant.name.slice(0, 1).toUpperCase()}</span><div><b>{tenant.name}</b><small>Plan {tenant.plan || 'Starter'}</small></div></div><nav><a onClick={() => router.push('/workspace')}>▦ <span>Resumen</span></a><a className="active">◈ <span>Plan y facturación</span></a><a onClick={() => router.push('/workspace/members')}>♙ <span>Usuarios y roles</span></a></nav></aside><section className="workspace-main billing-main"><header className="billing-header"><div><button className="text-link" onClick={() => router.push('/workspace')}>← Resumen</button><div className="eyebrow catalog-eyebrow">Tu espacio / Suscripción</div><h1>Planes y facturación</h1><p>Gestiona el plan de <strong>{tenant.name}</strong>.</p></div>{billing.subscription.hasPaymentCustomer && <button className="button button-secondary" onClick={() => void action('portal')} disabled={saving}>Administrar facturación ↗</button>}</header>{message && <div className="catalog-message">{message}</div>}<div className="billing-status"><div><small>Plan actual</small><strong>{billing.plans[billing.subscription.plan]?.name || billing.subscription.plan}</strong><span>{billing.plans[billing.subscription.plan]?.description || 'Configuración de suscripción'}</span></div><div><small>Estado</small><strong>{statusLabels[billing.subscription.status] || billing.subscription.status}</strong><span>{billing.subscription.cancelAtPeriodEnd ? 'Se cancelará al finalizar el período' : 'Renovación automática según Stripe'}</span></div></div><div className="plans-grid">{Object.entries(billing.plans).map(([key, plan]) => <article className={`plan-card ${key === billing.subscription.plan ? 'current' : ''}`} key={key}><span className="plan-badge">{key === billing.subscription.plan ? 'Plan actual' : 'SaaS'}</span><h2>{plan.name}</h2><p>{plan.description}</p><div className="plan-price">Configurable <small>por Stripe</small></div><button className="button" onClick={() => void action('checkout', key)} disabled={saving || key === billing.subscription.plan}>{key === billing.subscription.plan ? 'Plan seleccionado' : 'Elegir este plan ↗'}</button><ul><li>Espacio aislado por empresa</li><li>Módulos operativos y financieros</li><li>Soporte para permisos por rol</li></ul></article>)}</div><div className="billing-note"><b>Pagos seguros mediante Stripe.</b><span>Los datos de tarjeta se gestionan en páginas alojadas por Stripe. Esta aplicación no almacena números completos de tarjeta.</span></div></section></main>;
}

export default function BillingPage() { return <TenantProvider><BillingContent /></TenantProvider>; }
