alter table public.tenants add column if not exists platform_status text not null default 'active';
alter table public.tenants add column if not exists stripe_customer_id text;
alter table public.tenants add column if not exists stripe_subscription_id text;
alter table public.tenants add column if not exists subscription_current_period_end timestamptz;
alter table public.tenants add column if not exists cancel_at_period_end boolean not null default false;
alter table public.tenants add column if not exists last_stripe_event_created bigint;
alter table public.tenants add column if not exists plan_managed_by text;
alter table public.tenants add column if not exists plan_changed_at timestamptz;
alter table public.tenants add column if not exists plan_changed_by uuid references auth.users(id) on delete set null;
alter table public.tenants add column if not exists last_payment_failure_at timestamptz;
create unique index if not exists tenants_stripe_customer_idx on public.tenants(stripe_customer_id) where stripe_customer_id is not null;
create table if not exists public.api_keys (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, hash text not null unique, prefix text not null, label text not null default 'API key', status text not null default 'active' check (status in ('active','revoked')), created_by uuid references auth.users(id) on delete set null, created_at timestamptz not null default now(), last_used_at timestamptz, unique(id,tenant_id));
create index if not exists api_keys_hash_idx on public.api_keys(hash);
create table if not exists public.integration_events (id uuid primary key default gen_random_uuid(), tenant_id uuid not null references public.tenants(id) on delete cascade, event_id text not null, event_type text not null, data jsonb not null default '{}'::jsonb, received_at timestamptz not null default now(), status text not null default 'received', source text not null default 'preview-webhook', unique(tenant_id,event_id));
create table if not exists public.billing_events (id uuid primary key default gen_random_uuid(), event_id text not null unique, event_type text not null, stripe_created bigint not null, status text not null default 'received', retry_count integer not null default 0, received_at timestamptz not null default now(), processing_started_at timestamptz, processed_at timestamptz, failed_at timestamptz, error text, updated_at timestamptz not null default now());
create table if not exists public.platform_audit (id uuid primary key default gen_random_uuid(), actor_uid uuid, tenant_id uuid references public.tenants(id) on delete set null, action text not null, details jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
create index if not exists platform_audit_created_idx on public.platform_audit(created_at desc);
revoke all on table public.api_keys, public.integration_events, public.billing_events, public.platform_audit from anon, authenticated;
grant select on table public.platform_audit to authenticated;
